version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ./scripts/start
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=password