#! /usr/local/bin/ruby

require 'dotenv/load'
require 'rubygems'
require 'bundler'

Bundler.require

require "./db/connect"

Dir['./models/*.rb'].each {|file| require file }
Dir['./lib/*.rb'].each {|file| require file }

pry