#! /usr/local/bin/ruby

require 'dotenv/load'
require './db/connect'

Sequel.extension :migration

if ARGV[0]
  target = ARGV[0].to_i
else 
  target = nil
end

Sequel::Migrator.run(DB, "db/migrations", target: target)